# Generated by Django 3.2.18 on 2023-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20230313_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cameraVideo',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
