# Generated by Django 3.2.16 on 2023-02-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survallence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
