# Generated by Django 3.2.18 on 2023-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField()),
                ('resetCode', models.CharField(max_length=6)),
            ],
        ),
    ]
