# Generated by Django 3.2.18 on 2023-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
