# Generated by Django 3.2.18 on 2023-05-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_forgotpassword'),
        ('metaData', '0002_alter_metadata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
