# Generated by Django 3.2.18 on 2023-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0003_metadata_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='metadata',
            name='video_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
