# Generated by Django 3.2.16 on 2023-03-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('policemans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='polieman',
            new_name='policeman',
        ),
    ]
